name: open_ui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  window_manager: ^0.3.7
  flutter_svg: ^2.0.9
  markdown_widget: ^2.2.0
  video_player: ^2.7.2
  # 请求接口
  http: ^0.13.3
  # 图标
  fluentui_system_icons: ^1.1.222
  #提示通知
  flutter_toastr: ^1.0.3
  #math equation rendering
  flutter_math_fork: ^0.7.1
  #html tag parser
  html: ^0.15.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
